controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

app_user_edit_email:
    path: /user/edit/email
    controller: App\Controller\UserController::editEmail

app_user_edit_pseudo:
    path: /user/edit/pseudo
    controller: App\Controller\UserController::editPseudo

partenaire_detail:
    path: '/partenaires/{id}'
    controller: App\Controller\PartenaireController::show
    requirements:
        id: \d+

app_evenementiel:
    path: /evenementiel
    controller: App\Controller\EvenementielController::index

# config/routes.yaml

page_informations_ascension:
    path: /page_informations_ascension
    controller: App\Controller\EvenementielController::pageInformationsAscension

page_informations_anima:
    path: /page_informations_anima
    controller: App\Controller\EvenementielController::pageInformationsAnima

liste_equipes:
    path: /equipes
    controller: App\Controller\EquipeController::listeEquipes

afficher_equipe:
    path: /equipe/{id}
    controller: App\Controller\EquipeController::afficherEquipe