controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

app_user_edit_email:
    path: /user/edit/email
    controller: App\Controller\UserController::editEmail

app_user_edit_pseudo:
    path: /user/edit/pseudo
    controller: App\Controller\UserController::editPseudo